---
title: "mir199 differential expression"
output:
  html_document:
    df_print: paged
---

Load the required libraries
```{r include=FALSE}
library(DESeq2)
library(BiocParallel)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(EnsDb.Hsapiens.v103)
library(biomaRt)
library(readxl)
library(org.Hs.eg.db)
library(GOSemSim)
library(writexl)
library(feather)
library(httr)
library(ggsci)
library(RColorBrewer)

source("src/utilityFunctions.R")
source("src/GOEnrichment.R")
```


Run the differential expression analysis using the counts matrix from kallisto/tximport
```{r include=FALSE}
#get the metadata and the counts x gene matrix from the pipeline
sampleTable <- "data/HAC_mir199_sampleTable.txt"
comparisonsTable <- "data/HAC_mir199_comparisons.txt"
txiData  <- "data/HAC_mir199_txi.RDS"

#run the differential expression pipeline
res <- runDiffExp(txiData,sampleTable,comparisonsTable,OATargets = NULL,c("Donor","Condition"),c("Donor","Condition"),"mir199_mRNADiff.txt",saveCounts = TRUE)

#get the number of up and down differentially expressed genes
mir199_5p <- res$cutTables[[1]]
numUp <- nrow(na.omit(mir199_5p[mir199_5p$hp199avshpC_log2FoldChange >= log2(1.3) & mir199_5p$hp199avshpC_padj <=0.05,]))
sprintf("number upregulated genes is %d",numUp)

numDown <- nrow(na.omit(mir199_5p[mir199_5p$hp199avshpC_log2FoldChange <= log2(1/1.3) & mir199_5p$hp199avshpC_padj <=0.05,]))
sprintf("number downregulated genes is %d",numDown)

```

Get predicted targets for mir199 and compare with the fold change upon mir199 knockdown
```{r include=FALSE}
#get the target scan data
targetscan <- read.delim("https://www.targetscan.org/vert_80/temp/TargetScan8.0__miR-199-5p.predicted_targets.txt")

#get the TPMs for each gene
TPMs <- readRDS("data/HAC_mir199_txi.RDS")
TPMs <- stack(rowMeans(TPMs$abundance))

#plot the fold change of the predicted mir199 targets
mir199Targets <- targetPlot(res$cutTables[[1]],targetscan,TPMs)



#add the ACL data for comparison
aclDiffExp <- readRDS("data/D7ACLvsNaive_diffExp.RDS")
human2geneTable <- convertHumanGeneList(mir199Targets$targets$gene_name)

aclDiffExp <- merge(aclDiffExp,human2geneTable,by.x="gene_name",by.y="MGI.symbol")
mir199.targets <- merge(mir199Targets$targets,aclDiffExp,by.x="gene_name",by.y="HGNC.symbol")  

mir199.targets.filt <- mir199.targets[ mir199.targets$hp199avshpC_padj<=0.05 & mir199.targets$hp199avshpC_log2FoldChange>0,]
mir199.targets.filt <- mir199.targets.filt[ mir199.targets.filt$day_7_rightvsday_7_naive_padj<=0.05,]

mir199.targets.filt <- mir199.targets.filt[ order(mir199.targets.filt$Predicted.occupancy..low.miRNA.,decreasing = TRUE),]


colnames(mir199.targets)[c(2,26,27)] <- c("HumanID","MouseID","mouse_gene_name")


#get the mirDIP targets
mirDIP <- getMirDipTargets("hsa-miR-199a-5p")


write_xlsx(list(filtered=mir199.targets.filt,all=mir199.targets,mirDIP=mirDIP),"results/mir1995pTargets.xlsx")


#write out table of results
#save the differential expression tables
cutTables <- res$cutTables
names(cutTables) <- c("mir199aInhibitionvsCtrl","mir199bInhibitionvsCtrl")
write_xlsx(c(cutTables,list(mir199.targetscan=mir199.targets,mir199.mirDIP=mirDIP)),"results/SupplementryTable5.xlsx")
```

Gene ontology plot of the differential expression
```{r include=FALSE}

#get the gene lengths
geneLengths <- read.delim("data/humanGeneLengths.txt")

#format the differential expresson data
mir199KDDiffExp <- res$cutTables[[1]]
mir199KDDiffExp <- mir199KDDiffExp[,c(4,2,3,1)]

#get the enriched gene ontology terms
# goresults <- GOEnrichment(differentialExpression = mir199KDDiffExp,geneLengths = geneLengths,species = "Human",foldChangeOnly = FALSE,foldchange = 1 ,padj = 0.05 )
#get the enriched gene ontology terms - up
goresults.up <- GOEnrichment(differentialExpression = mir199KDDiffExp,geneLengths = geneLengths,species = "Human",foldChangeOnly = FALSE,foldchange = 1 ,padj = 0.05, direction="up" ,decreaseSize=FALSE )

goresults.down <- GOEnrichment(differentialExpression = mir199KDDiffExp,geneLengths = geneLengths,species = "Human",foldChangeOnly = FALSE,foldchange = 1 ,padj = 0.05,  direction="down",decreaseSize=FALSE )




#save the result
write_xlsx(list(Upregulated=goresults.up[[1]],DownRegulated=goresults.down[[1]]),"results/SupplementryTable6.xlsx")

IDs <- c("GO:0030574","GO:1902253","GO:0031571","GO:0034728","GO:0006334","GO:0032502","GO:0045653")
goPlot <- plotEnrichment(goresults.up[[1]],8,IDs)


```


Comparison to skeletalvis
```{r include=FALSE}
accessions <- read.delim("data/accessions.txt")
accessions$combined <- paste(accessions$accession,accessions$comparison,sep="_")
foldchangeTable <- as.data.frame(read_feather("data/foldChangeTable.feather"))
rownames(foldchangeTable)<- foldchangeTable$ID

sims <-  getSim(mir199KDDiffExp,foldchangeTable,accessions,"mir199")
sims <- sims[ order(sims$zscore,decreasing =TRUE),c("accession","comparisonsText","zscore")]


write_xlsx(sims,"results/SupplementryTable7.xlsx")

```


Save all the plots
```{r}
save_plot("figures/Fig3A_volcano.png",res$volcano[[1]],base_height = 6,base_width = 6,bg="white")
save_plot("figures/Fig3B_targets.png",mir199Targets$plot,base_height = 6,base_width = 6,bg="white")
save_plot("figures/Fig3C_GOPlot.png",goPlot,base_height = 11,base_width = 11,bg="white")
```

